### register
PUT http://localhost:8000/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane2@john.com",
  "password": "Aa12345!",
  "confirmPassword": "Aa12345!"
}

### login
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "jane3@doe.com",
  "password": "Aa12345!"
}

### logout
POST http://localhost:8000/users/logout
Content-Type: application/json

### update user profile
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane3@doe.com",
  "password": "Aa12345!",
  "confirmPassword": "Aa12345!"
}